modLoader="javafml"
loaderVersion="[47,)"
license="ARR"
issueTrackerURL="https://github.com/QLNPLUS/qshop-sell-upgrade/issues"

[[mods]]
modId="qshop_sell_upgrade"
version="0.1.0"
displayName="QShop Sell Upgrade"
authors="QShop"
description='''
Automatically sells priced picked-up items instead of storing them in Sophisticated Backpacks.
'''

[[dependencies.qshop_sell_upgrade]]
modId="forge"
mandatory=true
versionRange="[47,48)"
ordering="NONE"
side="BOTH"

[[dependencies.qshop_sell_upgrade]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.qshop_sell_upgrade]]
modId="qshop"
mandatory=true
versionRange="[1.1.0,2.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.qshop_sell_upgrade]]
modId="qshop_sellbox"
mandatory=true
versionRange="[1.0.0,2.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.qshop_sell_upgrade]]
modId="sophisticatedbackpacks"
mandatory=true
versionRange="[3.0,4.0)"
ordering="AFTER"
side="BOTH"

[[dependencies.qshop_sell_upgrade]]
modId="sophisticatedcore"
mandatory=true
versionRange="[1.3.6.1514,)"
ordering="AFTER"
side="BOTH"
